target-certs:; @true
target-extension:; @true
target-external_libs/mbedtls:; @true
target-external_libs/nghttp2:; @true
target-src/atm:; @true
target-src/coap:; @true
target-src/dev_bind:; @true
target-src/dev_model:; @true
target-src/dev_reset:; @true
target-src/dev_sign:; @true
target-src/dynamic_register:; @true
target-src/http:; @true
target-src/http2:; @true
target-src/infra:; @true
target-src/mqtt:; @true
target-src/ota:; @true
target-src/shadow:; @true
target-src/wifi_provision:; @true
target-wrappers:; @true
