#!/bin/sh /etc/rc.common
START=99

BASE_PATH="/userdata"
start() {
    echo "Starting honyar: "
    cd $BASE_PATH/hyapp && ./hylinkapp > /dev/null &
    cd $BASE_PATH/app && ./mqttapp &
    cd $BASE_PATH/iotapp && ./tyzigbeeapp > /dev/null &
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo "Stopping honyar: "
    killall mqttapp tyzigbeeapp hylinkapp
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
:<<!
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
!